from __future__ import annotations

from datetime import date

from sources.devevents import DevEventsSource


def test_devevents_filters_to_hackathon_tag(fixture_response, monkeypatch):
    response = fixture_response("devevents.xml")
    monkeypatch.setattr("sources.devevents.get", lambda *a, **k: response)

    hackathons = DevEventsSource().fetch()

    assert len(hackathons) == 2
    titles = {h.title for h in hackathons}
    assert titles == {"Test Hack Night", "Offline Build Sprint"}
    assert "Not A Hackathon Meetup" not in titles


def test_devevents_parses_online_and_location(fixture_response, monkeypatch):
    response = fixture_response("devevents.xml")
    monkeypatch.setattr("sources.devevents.get", lambda *a, **k: response)

    hackathons = {h.title: h for h in DevEventsSource().fetch()}

    online = hackathons["Test Hack Night"]
    assert online.is_online is True
    assert online.location == "Online"
    assert online.starts_at == date(2026, 8, 25)

    offline = hackathons["Offline Build Sprint"]
    assert offline.is_online is False
    assert offline.location == "Basel, Switzerland, Europe"
    assert offline.starts_at == date(2026, 10, 30)


def test_devevents_returns_empty_on_garbage(monkeypatch):
    from conftest import FakeResponse

    monkeypatch.setattr("sources.devevents.get", lambda *a, **k: FakeResponse("<not>rss</not>"))
    assert DevEventsSource().fetch() == []


def test_devevents_enrich_adds_end_date_and_attendance_mode(fixture_response, monkeypatch):
    """RSS carries no end date at all, so this is the field enrichment exists for."""
    monkeypatch.setattr(
        "sources.devevents.get", lambda *a, **k: fixture_response("devevents_detail.html")
    )
    h = _listing_item()

    enriched = DevEventsSource().enrich(h)

    assert enriched.ends_at == date(2026, 9, 20)
    assert enriched.is_online is True


def test_devevents_enrich_drops_autogenerated_description(fixture_response, monkeypatch):
    """dev.events synthesises 'Crypto / Blockchain hackathon Online' from the
    category — it repeats the card and must not be shown as a description."""
    monkeypatch.setattr(
        "sources.devevents.get", lambda *a, **k: fixture_response("devevents_detail.html")
    )

    assert DevEventsSource().enrich(_listing_item()).description is None


def test_devevents_enrich_skips_organizer_echoing_the_title(fixture_response, monkeypatch):
    """performer.name is usually just the event name again."""
    monkeypatch.setattr(
        "sources.devevents.get", lambda *a, **k: fixture_response("devevents_detail.html")
    )

    assert DevEventsSource().enrich(_listing_item()).organizer is None


def test_devevents_enrich_keeps_listing_values_when_page_is_useless(monkeypatch):
    """No schema.org block (client-render changed): pass through, never blank out."""
    from conftest import FakeResponse

    monkeypatch.setattr(
        "sources.devevents.get", lambda *a, **k: FakeResponse("<html><body>nope</body></html>")
    )
    h = _listing_item(is_online=True, location="Online")

    enriched = DevEventsSource().enrich(h)

    assert enriched.is_online is True
    assert enriched.location == "Online"
    assert enriched.starts_at == date(2026, 8, 27)


_IFRAME_PAGE = (
    '<html><body><div class="iframe-wrapper">'
    '<iframe title="embedded event\'s website" '
    'src="https://dorahacks.io/hackathon/agent-economy/detail"></iframe>'
    "</div></body></html>"
)


def test_devevents_enrich_follows_iframe_to_real_event_site(monkeypatch):
    """Externally-hosted events are wrapped in an iframe; the wrapper has no
    real content (and often errors), so the url must point at the target."""
    from conftest import FakeResponse

    monkeypatch.setattr("sources.devevents.get", lambda *a, **k: FakeResponse(_IFRAME_PAGE))

    enriched = DevEventsSource().enrich(_listing_item())

    assert enriched.url == "https://dorahacks.io/hackathon/agent-economy/detail"
    assert enriched.title == _listing_item().title  # nothing else clobbered


def test_devevents_enrich_ignores_self_referential_or_relative_iframe(monkeypatch):
    from conftest import FakeResponse

    page = (
        '<html><body><div class="iframe-wrapper">'
        '<iframe src="https://dev.events/embed/thing"></iframe>'
        "</div></body></html>"
    )
    monkeypatch.setattr("sources.devevents.get", lambda *a, **k: FakeResponse(page))
    h = _listing_item()

    assert DevEventsSource().enrich(h).url == h.url


def test_devevents_enrich_keeps_url_when_no_iframe(fixture_response, monkeypatch):
    """Self-hosted events have no iframe — the dev.events url stays."""
    monkeypatch.setattr(
        "sources.devevents.get", lambda *a, **k: fixture_response("devevents_detail.html")
    )
    h = _listing_item()

    assert DevEventsSource().enrich(h).url == h.url


def test_devevents_enrich_survives_fetch_failure(monkeypatch):
    def boom(*a, **k):
        raise RuntimeError("connection reset")

    monkeypatch.setattr("sources.devevents.get", boom)
    h = _listing_item()

    assert DevEventsSource().enrich(h) == h


def _listing_item(**overrides):
    from sources.base import Hackathon

    defaults = dict(
        source="devevents",
        source_id="https://dev.events/conferences/chain-jam-vol-1-lc37xek8",
        title="Chain Jam Vol. 1",
        url="https://dev.events/conferences/chain-jam-vol-1-lc37xek8",
        starts_at=date(2026, 8, 27),
        ends_at=None,
        is_online=None,
        prize_text=None,
        location=None,
        themes=["Crypto / Blockchain", "hackathon"],
    )
    defaults.update(overrides)
    return Hackathon(**defaults)
